build:
  cache:
    paths:
      - node_modules/
  stage: build
  rules:
    - if: $GITLAB_AC_PARIS == null
      when: never
  image: node:20
  script:
    - npm install
    - npm run generate
  artifacts:
    paths:
      - .output/public/

deploy:
  stage: deploy
  rules:
    - if: $GITLAB_AC_PARIS == null
      when: never
    - if: $PROD_AUTO_DEPLOY
      when: on_success
    - if: $CI_COMMIT_BRANCH == "main"
      when: manual
    - when: on_success
  image: tjaisson/rsync
  script:
    - mkdir -p ~/.ssh/
    - mv $SSH_PRIVATE_KEY ~/.ssh/id_rsa
    - chmod a-r-w-x,u+r ~/.ssh/id_rsa
    - mv $SSH_CONFIG ~/.ssh/config
    - chmod a-r-w-x,u+r ~/.ssh/config
    - FOLDER="/home/gitdeploy"
    - TARGET="vue-frontend"
    - URL="${CI_COMMIT_BRANCH}:${FOLDER}/${TARGET}"
    - rsync -avzP --delete .output/public/ "${URL}/"
